name: OreRatio
version: 0.1.0
main: fr.sandro642.github.OreRatio
author: Sandro642
website: https://github.com/Sandro642/OreRatio
api-version: '1.21.11'
commands:
  oreratio:
    permission: oreratio.use